version: '2'

networks:
  proxy:
    external:
      name: nginxproxy_default

services:
 globalsight:
   build: ./gs/
   image: locpeople/globalsight
   container_name: globalsight
   ports:
    - 4567:80

   volumes:
    - gs_filestorage:/home/jboss/fileStorage
    - gs_docs:/home/jboss/docs
   networks:
    - default
    - proxy

 globalsight_db:
   image: mysql:5.7
   container_name: globalsight_db
   environment:
     - MYSQL_DATABASE=globalsight
     - MYSQL_ROOT_PASSWORD=root
   volumes:
    - gs_database:/var/mysql/data
    - ./db:/etc/mysql/conf.d

volumes:
  gs_filestorage:
  gs_docs:
  gs_database: